const products = [
    {
      _id: '1',
      name: 'Airpods Wireless Bluetooth Headphones',
      image: '/image/10.png',
      description:
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
      brand: 'Apple',
      category: 'Electronics',
      price: "190",
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'iPhone 12 Pro 256GB Memory',
      image: '/image/20.png',
      description:
        'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
      brand: 'Apple',
      category: 'Electronics',
      price: 1400,
      countInStock: 7,
      rating: 4.0,
      numReviews: 8,
    },
    {
      _id: '3',
      name: 'Cannon EOS 80D DSLR Camera',
      image: '/image/60.png',
      description:
        'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
      brand: 'Cannon',
      category: 'Electronics',
      price: 900,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '4',
      name: 'Sony Playstation 4 Pro White Version',
      image: '/image/40.png',
      description:
        'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
      brand: 'Sony',
      category: 'Electronics',
      price: 350,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Logitech G-Series Gaming Mouse',
      image: '/image/30.png',
      description:
        'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
      brand: 'Logitech',
      category: 'Electronics',
      price:  160,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '6',
      name: 'Amazon Echo Dot 3rd Generation',
      image: '/image/50.png',
      description:
        'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
      brand: 'Amazon',
      category: 'Electronics',
      price: 220,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
      _id: '7',
      name: 'Airpods Wireless Bluetooth Headphones',
      image: '/image/10.png',
      description:
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
      brand: 'Apple',
      category: 'Electronics',
      price: 190,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '8',
      name: 'Logitech G-Series Gaming Mouse',
      image: '/image/30.png',
      description:
        'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
      brand: 'Logitech',
      category: 'Electronics',
      price:  160,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '9',
      name: 'Sony Playstation 4 Pro White Version',
      image: '/image/40.png',
      description:
        'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
      brand: 'Sony',
      category: 'Electronics',
      price: 350,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
        _id: '10',
        name: 'Amazon Echo Dot 3rd Generation',
        image: '/image/50.png',
        description:
          'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        brand: 'Amazon',
        category: 'Electronics',
        price: 220,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '11',
        name: 'iPhone 12 Pro 256GB Memory',
        image: '/image/20.png',
        description:
          'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
        brand: 'Apple',
        category: 'Electronics',
        price: 1400 ,
        countInStock: 7,
        rating: 4.0,
        numReviews: 8,
      },
      {
        _id: '12',
        name: 'Sony Playstation 4 Pro White Version',
        image: '/image/40.png',
        description:
          'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
        brand: 'Sony',
        category: 'Electronics',
        price: 350,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
      },
  ]
  
  export default products